[workspace]
resolver = "2"
members = [
    "crates/pawchat-kv-core",
    "crates/pawchat-kv-server",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["ybanas"]
repository = "https://github.com/mairie-creusot/pawchat-kv"

[workspace.dependencies]
pawchat-kv-core = { path = "crates/pawchat-kv-core" }

[profile.release]
opt-level = 3
lto = "thin"

[profile.bench]
opt-level = 3
lto = "thin"
debug = true
